name: flutter_hf
description: Studio ghibli movies list app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # network
  json_annotation: ^4.0.0
  http: ^0.13.0
  # provider
  provider: ^5.0.0
  # shared prefs
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  # generator
  build_runner: ^1.12.2
  json_serializable: ^4.0.3

flutter:
  uses-material-design: true